'use strict';
// Fabric server creation/deletion via the Fabric meta API (meta.fabricmc.net).
// New servers default to Fabric using the latest stable loader + installer.
const fs = require('fs');
const fsp = fs.promises;
const path = require('path');
const crypto = require('crypto');
const { execFile, execFileSync } = require('child_process');
const { promisify } = require('util');
const execFileP = promisify(execFile);
const cfg = require('./config');
const mc = require('./mc');
const paper = require('./paper');

const META = 'https://meta.fabricmc.net/v2';
const MODRINTH = 'https://api.modrinth.com/v2';
const UA = { 'User-Agent': 'shaurycontroller-panel/1.0 (apsood@gmail.com)' };

// Direct URL to a ready-to-run Fabric server launcher jar.
function serverJarUrl(mcVersion, loader, installer) {
  return `${META}/versions/loader/${encodeURIComponent(mcVersion)}/${encodeURIComponent(loader)}/${encodeURIComponent(installer)}/server/jar`;
}
function serverJarName(mcVersion, loader, installer) {
  return `fabric-server-mc.${mcVersion}-loader.${loader}-launcher.${installer}.jar`;
}

async function getJSON(url) {
  const res = await fetch(url, { headers: UA });
  if (!res.ok) throw new Error('fetch ' + url + ' -> ' + res.status);
  return res.json();
}

async function gameVersions() {
  const list = await getJSON(META + '/versions/game');
  return list.map((v) => ({ version: v.version, stable: !!v.stable }));
}

async function latestStable(kind) { // 'loader' | 'installer'
  const list = await getJSON(META + '/versions/' + kind);
  const norm = list.map((x) => (kind === 'loader' ? x : x)); // both expose .version/.stable at top level
  const stable = norm.find((x) => x.stable) || norm[0];
  return stable.version;
}

async function metaInfo() {
  const [games, loader, installer] = await Promise.all([
    gameVersions(),
    latestStable('loader'),
    latestStable('installer'),
  ]);
  return { games, latestLoader: loader, latestInstaller: installer };
}

function slugify(name) {
  const s = String(name).trim().toLowerCase().replace(/[^a-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '');
  return s;
}

// Pick a free TCP port not used by an existing panel server and not currently listening.
function findFreePort() {
  const used = new Set(cfg.load().servers.map((s) => s.port).filter(Boolean));
  let listening = new Set();
  try {
    const out = execFileSync('ss', ['-tlnH'], { encoding: 'utf8' });
    for (const line of out.split('\n')) {
      const m = line.match(/:(\d+)\s/);
      if (m) listening.add(parseInt(m[1], 10));
    }
  } catch {}
  for (let p = 25565; p <= 25700; p++) {
    if (!used.has(p) && !listening.has(p)) return p;
  }
  throw new Error('no free port found in 25565-25700');
}

async function createServer({ name, mcVersion, type = 'fabric', loaderVersion, installerVersion, memory }) {
  const id = slugify(name);
  if (!id) throw Object.assign(new Error('invalid server name'), { status: 400 });
  const conf = cfg.load();
  if (conf.servers.some((s) => s.id === id)) throw Object.assign(new Error('a server with that name already exists'), { status: 409 });
  const dir = cfg.serverDir(id);
  if (fs.existsSync(dir)) throw Object.assign(new Error('directory already exists: ' + dir), { status: 409 });
  if (!mcVersion) throw Object.assign(new Error('mcVersion is required'), { status: 400 });
  if (!/^[0-9A-Za-z._-]+$/.test(mcVersion)) throw Object.assign(new Error('invalid mcVersion'), { status: 400 });
  if (memory && !/^\d+[kKmMgG]?$/.test(String(memory))) throw Object.assign(new Error('invalid memory (e.g. 4G)'), { status: 400 });
  if (type !== 'fabric' && type !== 'paper') throw Object.assign(new Error('type must be fabric or paper'), { status: 400 });

  await fsp.mkdir(dir, { recursive: true });
  try {
    let jarName, meta;
    if (type === 'paper') {
      const r = await paper.downloadInto(dir, mcVersion);
      jarName = r.jar; meta = { type: 'paper', paperBuild: r.build };
    } else {
      const loader = loaderVersion || await latestStable('loader');
      const installer = installerVersion || await latestStable('installer');
      const res = await fetch(serverJarUrl(mcVersion, loader, installer), { headers: UA });
      if (!res.ok) throw new Error('failed to download Fabric server jar (' + res.status + ') for MC ' + mcVersion);
      jarName = serverJarName(mcVersion, loader, installer);
      await fsp.writeFile(path.join(dir, jarName), Buffer.from(await res.arrayBuffer()));
      meta = { type: 'fabric', loader, installer };
    }

    const port = findFreePort();
    await fsp.writeFile(path.join(dir, 'eula.txt'), 'eula=true\n');
    // Minimal server.properties; the server fills in remaining defaults on first launch.
    await fsp.writeFile(path.join(dir, 'server.properties'),
      ['# Generated by shaurycontroller panel', 'server-port=' + port, 'sync-chunk-writes=false', 'motd=' + id, ''].join('\n'));

    const server = {
      id, name: id, mcVersion, jar: jarName,
      java: cfg.JAVA_DEFAULT, memory: memory || '4G', jvmArgs: cfg.DEFAULT_FLAGS,
      port, createdAt: new Date().toISOString(), ...meta,
    };
    conf.servers.push(server);
    cfg.save(conf);
    return server;
  } catch (err) {
    try { await fsp.rm(dir, { recursive: true, force: true }); } catch {}
    throw err;
  }
}

async function deleteServer(id, { deleteFiles = true } = {}) {
  const conf = cfg.load();
  const idx = conf.servers.findIndex((s) => s.id === id);
  if (idx === -1) throw Object.assign(new Error('no such server'), { status: 404 });
  if (mc.isRunning(id)) await mc.stop(id);
  conf.servers.splice(idx, 1);
  cfg.save(conf);
  if (deleteFiles) {
    try { await fsp.rm(cfg.serverDir(id), { recursive: true, force: true }); } catch {}
  }
  // Clean run artifacts (keep backups).
  for (const f of [cfg.runLog(id), path.join(cfg.RUN_DIR, id + '.start.sh')]) {
    try { await fsp.rm(f, { force: true }); } catch {}
  }
  return true;
}

// ---------------------------------------------------------------------------
// Jar management for existing servers
// ---------------------------------------------------------------------------

// Auto-detect server-launcher jars in a server's working directory (top-level *.jar).
async function listJars(id) {
  const dir = cfg.serverDir(id);
  const active = (cfg.getServer(id) || {}).jar;
  let names = [];
  try { names = await fsp.readdir(dir); } catch { return []; }
  const out = [];
  for (const n of names) {
    if (!n.toLowerCase().endsWith('.jar')) continue;
    try {
      const st = await fsp.stat(path.join(dir, n));
      if (st.isFile()) out.push({ name: n, size: st.size, mtime: st.mtimeMs, active: n === active });
    } catch {}
  }
  out.sort((a, b) => b.mtime - a.mtime);
  return out;
}

// Download a new Fabric server jar into the server dir and make it the active jar.
async function downloadServerJar(id, { type, mcVersion, loaderVersion, installerVersion } = {}) {
  const conf = cfg.load();
  const srv = conf.servers.find((s) => s.id === id);
  if (!srv) throw Object.assign(new Error('no such server'), { status: 404 });
  if (!mcVersion) throw Object.assign(new Error('mcVersion is required'), { status: 400 });
  if (!/^[0-9A-Za-z._-]+$/.test(mcVersion)) throw Object.assign(new Error('invalid mcVersion'), { status: 400 });
  const t = type || srv.type || 'fabric';
  if (t !== 'fabric' && t !== 'paper') throw Object.assign(new Error('type must be fabric or paper'), { status: 400 });

  if (t === 'paper') {
    const r = await paper.downloadInto(cfg.serverDir(id), mcVersion);
    srv.jar = r.jar; srv.mcVersion = mcVersion; srv.type = 'paper'; srv.paperBuild = r.build;
    delete srv.loader; delete srv.installer;
    cfg.save(conf);
    return { jar: r.jar, mcVersion, type: 'paper', build: r.build };
  }
  const loader = loaderVersion || await latestStable('loader');
  const installer = installerVersion || await latestStable('installer');
  const res = await fetch(serverJarUrl(mcVersion, loader, installer), { headers: UA });
  if (!res.ok) throw new Error('failed to download Fabric server jar (' + res.status + ') for MC ' + mcVersion);
  const jarName = serverJarName(mcVersion, loader, installer);
  await fsp.writeFile(path.join(cfg.serverDir(id), jarName), Buffer.from(await res.arrayBuffer()));

  srv.jar = jarName; srv.mcVersion = mcVersion; srv.type = 'fabric'; srv.loader = loader; srv.installer = installer;
  delete srv.paperBuild;
  cfg.save(conf);
  return { jar: jarName, mcVersion, type: 'fabric', loader, installer };
}

// Latest Modrinth fabric build for a project+game version.
async function modrinthLatest(slug, mcVersion) {
  const url = `${MODRINTH}/project/${slug}/version`
    + `?loaders=${encodeURIComponent('["fabric"]')}`
    + `&game_versions=${encodeURIComponent('["' + mcVersion + '"]')}`;
  const list = await getJSON(url);
  if (!Array.isArray(list) || !list.length) return null;
  const v = list[0]; // newest first
  const file = (v.files || []).find((f) => f.primary) || (v.files || [])[0];
  if (!file) return null;
  return { versionNumber: v.version_number, url: file.url, filename: file.filename, sha512: file.hashes && file.hashes.sha512 };
}

// Download (or update) Fabric API into the server's mods/ folder for its MC version.
async function installFabricApi(id, mcVersion) {
  const srv = cfg.getServer(id);
  const mcv = mcVersion || (srv && srv.mcVersion);
  if (!mcv) throw Object.assign(new Error('mcVersion is required'), { status: 400 });
  const latest = await modrinthLatest('fabric-api', mcv);
  if (!latest) throw new Error('no Fabric API build found on Modrinth for MC ' + mcv);

  const modsDir = path.join(cfg.serverDir(id), 'mods');
  await fsp.mkdir(modsDir, { recursive: true });
  const buf = Buffer.from(await (await fetch(latest.url, { headers: UA })).arrayBuffer());
  if (latest.sha512) {
    const got = crypto.createHash('sha512').update(buf).digest('hex');
    if (got !== latest.sha512) throw new Error('Fabric API checksum mismatch');
  }
  // Remove older fabric-api jars so we don't end up with duplicates.
  let removed = [];
  for (const f of await fsp.readdir(modsDir)) {
    if (/^fabric-api.*\.jar$/i.test(f) && f !== latest.filename) {
      try { await fsp.rm(path.join(modsDir, f)); removed.push(f); } catch {}
    }
  }
  await fsp.writeFile(path.join(modsDir, latest.filename), buf);
  return { file: latest.filename, version: latest.versionNumber, removed };
}

// Delete every top-level jar except the active one.
async function pruneJars(id) {
  const dir = cfg.serverDir(id);
  const jars = await listJars(id);
  const deleted = [];
  for (const j of jars) {
    if (j.active) continue;
    try { await fsp.rm(path.join(dir, j.name)); deleted.push(j.name); } catch {}
  }
  return { deleted, kept: jars.find((j) => j.active) ? jars.find((j) => j.active).name : null };
}

// ---------------------------------------------------------------------------
// Modrinth browser: search projects, fetch details/versions, install into a server
// ---------------------------------------------------------------------------
// Where a project type gets installed inside the server directory.
const TYPE_DIRS = {
  mod: 'mods', plugin: 'plugins', datapack: path.join('world', 'datapacks'),
  resourcepack: 'resourcepacks', shader: 'shaderpacks', shaderpack: 'shaderpacks',
};
// Loaders the server's platform can run, and which loaders a project type needs.
const PLUGIN_LOADERS = ['paper', 'spigot', 'bukkit', 'purpur', 'folia'];
function serverLoaders(server) { return server && server.type === 'paper' ? PLUGIN_LOADERS : ['fabric']; }
function loadersForType(projectType) {
  if (projectType === 'mod') return ['fabric'];
  if (projectType === 'plugin') return PLUGIN_LOADERS;
  return []; // datapack / resourcepack / shader are not loader-filtered
}
// Modrinth reports project_type "mod" even for Bukkit/Paper plugins, so a hit's project_type
// is unreliable. Collapse the loadable categories (mod/plugin) to whatever THIS server actually
// loads; content types (datapack/resourcepack/shader) keep their own folder regardless of platform.
const CONTENT_TYPES = ['datapack', 'resourcepack', 'shader', 'shaderpack'];
function effectiveType(server, requestedType) {
  if (CONTENT_TYPES.includes(requestedType)) return requestedType;
  return server && server.type === 'paper' ? 'plugin' : 'mod';
}
const folderFor = (server) => (server && server.type === 'paper' ? 'plugins' : 'mods');

async function modrinthSearch({ query = '', projectType = 'mod', gameVersion = '', offset = 0, limit = 20 } = {}) {
  const loaders = loadersForType(projectType);
  const facets = [['project_type:' + projectType]];
  if (gameVersion) facets.push(['versions:' + gameVersion]);
  if (loaders.length) facets.push(loaders.map((l) => 'categories:' + l)); // OR-group of loaders
  const index = query ? 'relevance' : 'downloads';
  const url = `${MODRINTH}/search?limit=${limit}&offset=${offset}&index=${index}`
    + `&query=${encodeURIComponent(query)}&facets=${encodeURIComponent(JSON.stringify(facets))}`;
  const d = await getJSON(url);
  return {
    total: d.total_hits,
    hits: (d.hits || []).map((h) => ({
      slug: h.slug, projectId: h.project_id, title: h.title, description: h.description,
      author: h.author, iconUrl: h.icon_url, downloads: h.downloads, follows: h.follows,
      projectType: h.project_type, categories: h.categories, serverSide: h.server_side, clientSide: h.client_side,
    })),
  };
}

async function modrinthProject(slug) {
  const p = await getJSON(`${MODRINTH}/project/${encodeURIComponent(slug)}`);
  return {
    slug: p.slug, title: p.title, description: p.description, body: p.body, iconUrl: p.icon_url,
    downloads: p.downloads, projectType: p.project_type, sourceUrl: p.source_url,
    clientSide: p.client_side, serverSide: p.server_side, gameVersions: p.game_versions, loaders: p.loaders,
  };
}

async function modrinthVersions(slug, { loaders, gameVersion } = {}) {
  let url = `${MODRINTH}/project/${encodeURIComponent(slug)}/version`;
  const q = [];
  if (loaders && loaders.length) q.push('loaders=' + encodeURIComponent(JSON.stringify(loaders)));
  if (gameVersion) q.push('game_versions=' + encodeURIComponent('["' + gameVersion + '"]'));
  if (q.length) url += '?' + q.join('&');
  const list = await getJSON(url);
  return (list || []).map((v) => {
    const f = (v.files || []).find((x) => x.primary) || (v.files || [])[0] || {};
    return {
      id: v.id, name: v.name, versionNumber: v.version_number, versionType: v.version_type,
      gameVersions: v.game_versions, loaders: v.loaders, datePublished: v.date_published,
      filename: f.filename, url: f.url, sha512: f.hashes && f.hashes.sha512,
    };
  });
}

async function installFromModrinth(id, { slug, versionId, projectType = 'mod' } = {}) {
  const srv = cfg.getServer(id);
  if (!srv) throw Object.assign(new Error('no such server: ' + id), { status: 404 });
  if (!slug && !versionId) throw Object.assign(new Error('slug or versionId required'), { status: 400 });
  const mc = srv.mcVersion;
  // Derive the install type from the server's platform (not the caller-supplied / Modrinth
  // project_type, which can't distinguish a Paper plugin from a Fabric mod).
  const type = effectiveType(srv, projectType);
  const loaders = loadersForType(type);
  const platform = srv.type === 'paper' ? 'Paper' : 'Fabric';

  let chosen;
  if (versionId) {
    const v = await getJSON(`${MODRINTH}/version/${encodeURIComponent(versionId)}`);
    if (!(v.game_versions || []).includes(mc)) throw Object.assign(new Error(`that version supports MC ${(v.game_versions || []).join(', ') || '(none)'} — not ${mc}`), { status: 400 });
    if (loaders.length && !(v.loaders || []).some((l) => loaders.includes(l))) throw Object.assign(new Error(`that version is for ${(v.loaders || []).join('/') || '(no loader)'} — not compatible with ${platform}`), { status: 400 });
    const f = (v.files || []).find((x) => x.primary) || (v.files || [])[0];
    if (!f) throw new Error('version has no downloadable file');
    chosen = { filename: f.filename, url: f.url, sha512: f.hashes && f.hashes.sha512, versionNumber: v.version_number };
  } else {
    const vers = await modrinthVersions(slug, { loaders: loaders.length ? loaders : undefined, gameVersion: mc });
    if (!vers.length) throw Object.assign(new Error(`no compatible build of "${slug}" for MC ${mc}${loaders.length ? ' on ' + platform : ''}`), { status: 400 });
    chosen = vers[0];
  }
  const sub = TYPE_DIRS[type] || 'mods';
  const dir = path.join(cfg.serverDir(id), sub);
  await fsp.mkdir(dir, { recursive: true });
  const buf = Buffer.from(await (await fetch(chosen.url, { headers: UA })).arrayBuffer());
  if (chosen.sha512) {
    const got = crypto.createHash('sha512').update(buf).digest('hex');
    if (got !== chosen.sha512) throw new Error('checksum mismatch on ' + chosen.filename);
  }
  await fsp.writeFile(path.join(dir, chosen.filename), buf);
  return { file: chosen.filename, dir: sub, version: chosen.versionNumber };
}

// Identify installed mods via Modrinth hash lookup and flag MC-version conflicts.
async function installedMods(id) {
  const s = cfg.getServer(id);
  if (!s) throw Object.assign(new Error('no such server: ' + id), { status: 404 });
  const folder = folderFor(s); // mods/ for Fabric, plugins/ for Paper
  const okLoaders = serverLoaders(s);
  const modsDir = path.join(cfg.serverDir(id), folder);
  let files = [];
  try { files = (await fsp.readdir(modsDir)).filter((f) => f.toLowerCase().endsWith('.jar')); } catch { return { mcVersion: s.mcVersion, folder, mods: [] }; }

  const hashToFile = {};
  for (const f of files) {
    try { hashToFile[crypto.createHash('sha512').update(await fsp.readFile(path.join(modsDir, f))).digest('hex')] = f; } catch {}
  }
  const hashes = Object.keys(hashToFile);
  let byHash = {};
  if (hashes.length) {
    const res = await fetch(`${MODRINTH}/version_files`, {
      method: 'POST', headers: { ...UA, 'Content-Type': 'application/json' },
      body: JSON.stringify({ hashes, algorithm: 'sha512' }),
    });
    if (res.ok) byHash = await res.json();
  }
  const ids = [...new Set(Object.values(byHash).map((v) => v.project_id))];
  const projects = {};
  if (ids.length) {
    const pr = await fetch(`${MODRINTH}/projects?ids=${encodeURIComponent(JSON.stringify(ids))}`, { headers: UA });
    if (pr.ok) for (const p of await pr.json()) projects[p.id] = p;
  }
  const mods = [];
  for (const [hash, filename] of Object.entries(hashToFile)) {
    const v = byHash[hash];
    if (v) {
      const p = projects[v.project_id] || {};
      const vLoaders = v.loaders || [];
      const mcOk = (v.game_versions || []).includes(s.mcVersion);
      const loaderOk = !vLoaders.length || vLoaders.some((l) => okLoaders.includes(l));
      mods.push({
        filename, identified: true, slug: p.slug, projectId: v.project_id,
        title: p.title || p.slug || filename, iconUrl: p.icon_url, projectType: p.project_type || 'mod',
        versionNumber: v.version_number, gameVersions: v.game_versions || [], loaders: vLoaders,
        conflict: !mcOk || !loaderOk,
        conflictReason: !mcOk ? 'not built for MC ' + s.mcVersion : !loaderOk ? 'wrong loader (' + (vLoaders.join('/') || 'none') + ')' : null,
      });
    } else {
      mods.push({ filename, identified: false, conflict: false });
    }
  }
  mods.sort((a, b) => (a.conflict !== b.conflict ? (a.conflict ? -1 : 1) : (a.title || a.filename).localeCompare(b.title || b.filename)));
  return { mcVersion: s.mcVersion, folder, mods };
}

// Update a mod to the newest version for the server's MC + platform, removing the old jar.
async function updateMod(id, { slug, filename, projectType = 'mod' } = {}) {
  const s = cfg.getServer(id);
  if (!s) throw Object.assign(new Error('no such server: ' + id), { status: 404 });
  if (!slug) throw Object.assign(new Error('slug required'), { status: 400 });
  const r = await installFromModrinth(id, { slug, projectType });
  if (filename && filename !== r.file) {
    try { await fsp.rm(path.join(cfg.serverDir(id), r.dir || folderFor(s), filename)); } catch {}
  }
  return { ...r, replaced: filename };
}

// Import an uploaded world .zip: extract, locate level.dat, install as the server's
// `world` folder, and point level-name at it. Removes the zip when done.
async function importWorld(id, zipPath) {
  if (!cfg.getServer(id)) throw Object.assign(new Error('no such server: ' + id), { status: 404 });
  const dir = cfg.serverDir(id);
  const tmp = path.join(dir, '.world-import');
  const cleanup = async () => { await fsp.rm(tmp, { recursive: true, force: true }); await fsp.rm(zipPath, { force: true }); };
  await fsp.rm(tmp, { recursive: true, force: true });
  await fsp.mkdir(tmp, { recursive: true });
  try {
    await execFileP('unzip', ['-q', '-o', zipPath, '-d', tmp], { maxBuffer: 1 << 20 });
  } catch (e) { await cleanup(); throw new Error('failed to unzip: ' + (e.stderr || e.message)); }

  let levelDat = '';
  try {
    const { stdout } = await execFileP('find', [tmp, '-maxdepth', '6', '-name', 'level.dat'], { maxBuffer: 1 << 20 });
    levelDat = stdout.split('\n').filter(Boolean)[0] || '';
  } catch {}
  if (!levelDat) { await cleanup(); throw new Error('no level.dat found in the zip — not a valid Minecraft world'); }

  const worldRoot = path.dirname(levelDat);
  const dest = path.join(dir, 'world');
  await fsp.rm(dest, { recursive: true, force: true });
  await fsp.rename(worldRoot, dest);
  await fsp.rm(tmp, { recursive: true, force: true });
  await fsp.rm(zipPath, { force: true });
  cfg.setServerProperty(id, 'level-name', 'world');
  return { world: 'world' };
}

module.exports = {
  metaInfo, gameVersions, createServer, deleteServer, slugify, findFreePort,
  listJars, downloadServerJar, installFabricApi, pruneJars,
  modrinthSearch, modrinthProject, modrinthVersions, installFromModrinth,
  installedMods, updateMod, importWorld, loadersForType,
};
