'use strict';
// Fabric server creation/deletion via the Fabric meta API (meta.fabricmc.net).
// New servers default to Fabric using the latest stable loader + installer.
const fs = require('fs');
const fsp = fs.promises;
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');
const cfg = require('./config');
const mc = require('./mc');

const META = 'https://meta.fabricmc.net/v2';
const MODRINTH = 'https://api.modrinth.com/v2';
const UA = { 'User-Agent': 'shaurycontroller-panel/1.0 (apsood@gmail.com)' };

// Direct URL to a ready-to-run Fabric server launcher jar.
function serverJarUrl(mcVersion, loader, installer) {
  return `${META}/versions/loader/${encodeURIComponent(mcVersion)}/${encodeURIComponent(loader)}/${encodeURIComponent(installer)}/server/jar`;
}
function serverJarName(mcVersion, loader, installer) {
  return `fabric-server-mc.${mcVersion}-loader.${loader}-launcher.${installer}.jar`;
}

async function getJSON(url) {
  const res = await fetch(url, { headers: UA });
  if (!res.ok) throw new Error('fetch ' + url + ' -> ' + res.status);
  return res.json();
}

async function gameVersions() {
  const list = await getJSON(META + '/versions/game');
  return list.map((v) => ({ version: v.version, stable: !!v.stable }));
}

async function latestStable(kind) { // 'loader' | 'installer'
  const list = await getJSON(META + '/versions/' + kind);
  const norm = list.map((x) => (kind === 'loader' ? x : x)); // both expose .version/.stable at top level
  const stable = norm.find((x) => x.stable) || norm[0];
  return stable.version;
}

async function metaInfo() {
  const [games, loader, installer] = await Promise.all([
    gameVersions(),
    latestStable('loader'),
    latestStable('installer'),
  ]);
  return { games, latestLoader: loader, latestInstaller: installer };
}

function slugify(name) {
  const s = String(name).trim().toLowerCase().replace(/[^a-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '');
  return s;
}

// Pick a free TCP port not used by an existing panel server and not currently listening.
function findFreePort() {
  const used = new Set(cfg.load().servers.map((s) => s.port).filter(Boolean));
  let listening = new Set();
  try {
    const out = execFileSync('ss', ['-tlnH'], { encoding: 'utf8' });
    for (const line of out.split('\n')) {
      const m = line.match(/:(\d+)\s/);
      if (m) listening.add(parseInt(m[1], 10));
    }
  } catch {}
  for (let p = 25565; p <= 25700; p++) {
    if (!used.has(p) && !listening.has(p)) return p;
  }
  throw new Error('no free port found in 25565-25700');
}

async function createServer({ name, mcVersion, loaderVersion, installerVersion, memory }) {
  const id = slugify(name);
  if (!id) throw Object.assign(new Error('invalid server name'), { status: 400 });
  const conf = cfg.load();
  if (conf.servers.some((s) => s.id === id)) throw Object.assign(new Error('a server with that name already exists'), { status: 409 });
  const dir = cfg.serverDir(id);
  if (fs.existsSync(dir)) throw Object.assign(new Error('directory already exists: ' + dir), { status: 409 });
  if (!mcVersion) throw Object.assign(new Error('mcVersion is required'), { status: 400 });
  if (!/^[0-9A-Za-z._-]+$/.test(mcVersion)) throw Object.assign(new Error('invalid mcVersion'), { status: 400 });
  if (memory && !/^\d+[kKmMgG]?$/.test(String(memory))) throw Object.assign(new Error('invalid memory (e.g. 4G)'), { status: 400 });

  const loader = loaderVersion || await latestStable('loader');
  const installer = installerVersion || await latestStable('installer');

  await fsp.mkdir(dir, { recursive: true });
  try {
    // Download the ready-to-run Fabric server launcher jar.
    const res = await fetch(serverJarUrl(mcVersion, loader, installer), { headers: UA });
    if (!res.ok) throw new Error('failed to download Fabric server jar (' + res.status + ') for MC ' + mcVersion);
    const jarName = serverJarName(mcVersion, loader, installer);
    const buf = Buffer.from(await res.arrayBuffer());
    await fsp.writeFile(path.join(dir, jarName), buf);

    const port = findFreePort();
    await fsp.writeFile(path.join(dir, 'eula.txt'), 'eula=true\n');
    // Minimal server.properties; Minecraft fills in remaining defaults on first launch.
    await fsp.writeFile(path.join(dir, 'server.properties'),
      [
        '# Generated by shaurycontroller panel',
        'server-port=' + port,
        'sync-chunk-writes=false',
        'motd=' + id,
        '',
      ].join('\n'));

    const server = {
      id,
      name: id,
      mcVersion,
      loader,
      installer,
      jar: jarName,
      java: cfg.JAVA_DEFAULT,
      memory: memory || '4G',
      jvmArgs: cfg.DEFAULT_FLAGS,
      port,
      createdAt: new Date().toISOString(),
    };
    conf.servers.push(server);
    cfg.save(conf);
    return server;
  } catch (err) {
    // Roll back a half-created directory.
    try { await fsp.rm(dir, { recursive: true, force: true }); } catch {}
    throw err;
  }
}

async function deleteServer(id, { deleteFiles = true } = {}) {
  const conf = cfg.load();
  const idx = conf.servers.findIndex((s) => s.id === id);
  if (idx === -1) throw Object.assign(new Error('no such server'), { status: 404 });
  if (mc.isRunning(id)) await mc.stop(id);
  conf.servers.splice(idx, 1);
  cfg.save(conf);
  if (deleteFiles) {
    try { await fsp.rm(cfg.serverDir(id), { recursive: true, force: true }); } catch {}
  }
  // Clean run artifacts (keep backups).
  for (const f of [cfg.runLog(id), path.join(cfg.RUN_DIR, id + '.start.sh')]) {
    try { await fsp.rm(f, { force: true }); } catch {}
  }
  return true;
}

// ---------------------------------------------------------------------------
// Jar management for existing servers
// ---------------------------------------------------------------------------

// Auto-detect server-launcher jars in a server's working directory (top-level *.jar).
async function listJars(id) {
  const dir = cfg.serverDir(id);
  const active = (cfg.getServer(id) || {}).jar;
  let names = [];
  try { names = await fsp.readdir(dir); } catch { return []; }
  const out = [];
  for (const n of names) {
    if (!n.toLowerCase().endsWith('.jar')) continue;
    try {
      const st = await fsp.stat(path.join(dir, n));
      if (st.isFile()) out.push({ name: n, size: st.size, mtime: st.mtimeMs, active: n === active });
    } catch {}
  }
  out.sort((a, b) => b.mtime - a.mtime);
  return out;
}

// Download a new Fabric server jar into the server dir and make it the active jar.
async function downloadServerJar(id, { mcVersion, loaderVersion, installerVersion } = {}) {
  const conf = cfg.load();
  const srv = conf.servers.find((s) => s.id === id);
  if (!srv) throw Object.assign(new Error('no such server'), { status: 404 });
  if (!mcVersion) throw Object.assign(new Error('mcVersion is required'), { status: 400 });
  if (!/^[0-9A-Za-z._-]+$/.test(mcVersion)) throw Object.assign(new Error('invalid mcVersion'), { status: 400 });

  const loader = loaderVersion || await latestStable('loader');
  const installer = installerVersion || await latestStable('installer');
  const res = await fetch(serverJarUrl(mcVersion, loader, installer), { headers: UA });
  if (!res.ok) throw new Error('failed to download Fabric server jar (' + res.status + ') for MC ' + mcVersion);
  const jarName = serverJarName(mcVersion, loader, installer);
  await fsp.writeFile(path.join(cfg.serverDir(id), jarName), Buffer.from(await res.arrayBuffer()));

  srv.jar = jarName; srv.mcVersion = mcVersion; srv.loader = loader; srv.installer = installer;
  cfg.save(conf);
  return { jar: jarName, mcVersion, loader, installer };
}

// Latest Modrinth fabric build for a project+game version.
async function modrinthLatest(slug, mcVersion) {
  const url = `${MODRINTH}/project/${slug}/version`
    + `?loaders=${encodeURIComponent('["fabric"]')}`
    + `&game_versions=${encodeURIComponent('["' + mcVersion + '"]')}`;
  const list = await getJSON(url);
  if (!Array.isArray(list) || !list.length) return null;
  const v = list[0]; // newest first
  const file = (v.files || []).find((f) => f.primary) || (v.files || [])[0];
  if (!file) return null;
  return { versionNumber: v.version_number, url: file.url, filename: file.filename, sha512: file.hashes && file.hashes.sha512 };
}

// Download (or update) Fabric API into the server's mods/ folder for its MC version.
async function installFabricApi(id, mcVersion) {
  const srv = cfg.getServer(id);
  const mcv = mcVersion || (srv && srv.mcVersion);
  if (!mcv) throw Object.assign(new Error('mcVersion is required'), { status: 400 });
  const latest = await modrinthLatest('fabric-api', mcv);
  if (!latest) throw new Error('no Fabric API build found on Modrinth for MC ' + mcv);

  const modsDir = path.join(cfg.serverDir(id), 'mods');
  await fsp.mkdir(modsDir, { recursive: true });
  const buf = Buffer.from(await (await fetch(latest.url, { headers: UA })).arrayBuffer());
  if (latest.sha512) {
    const got = crypto.createHash('sha512').update(buf).digest('hex');
    if (got !== latest.sha512) throw new Error('Fabric API checksum mismatch');
  }
  // Remove older fabric-api jars so we don't end up with duplicates.
  let removed = [];
  for (const f of await fsp.readdir(modsDir)) {
    if (/^fabric-api.*\.jar$/i.test(f) && f !== latest.filename) {
      try { await fsp.rm(path.join(modsDir, f)); removed.push(f); } catch {}
    }
  }
  await fsp.writeFile(path.join(modsDir, latest.filename), buf);
  return { file: latest.filename, version: latest.versionNumber, removed };
}

// Delete every top-level jar except the active one.
async function pruneJars(id) {
  const dir = cfg.serverDir(id);
  const jars = await listJars(id);
  const deleted = [];
  for (const j of jars) {
    if (j.active) continue;
    try { await fsp.rm(path.join(dir, j.name)); deleted.push(j.name); } catch {}
  }
  return { deleted, kept: jars.find((j) => j.active) ? jars.find((j) => j.active).name : null };
}

// ---------------------------------------------------------------------------
// Modrinth browser: search projects, fetch details/versions, install into a server
// ---------------------------------------------------------------------------
// Where a project type gets installed inside the server directory.
const TYPE_DIRS = {
  mod: 'mods', plugin: 'plugins', datapack: path.join('world', 'datapacks'),
  resourcepack: 'resourcepacks', shader: 'shaderpacks', shaderpack: 'shaderpacks',
};

async function modrinthSearch({ query = '', projectType = 'mod', loader = 'fabric', gameVersion = '', offset = 0, limit = 20 } = {}) {
  const facets = [['project_type:' + projectType]];
  if (gameVersion) facets.push(['versions:' + gameVersion]);
  if (loader && projectType === 'mod') facets.push(['categories:' + loader]);
  const index = query ? 'relevance' : 'downloads';
  const url = `${MODRINTH}/search?limit=${limit}&offset=${offset}&index=${index}`
    + `&query=${encodeURIComponent(query)}&facets=${encodeURIComponent(JSON.stringify(facets))}`;
  const d = await getJSON(url);
  return {
    total: d.total_hits,
    hits: (d.hits || []).map((h) => ({
      slug: h.slug, projectId: h.project_id, title: h.title, description: h.description,
      author: h.author, iconUrl: h.icon_url, downloads: h.downloads, follows: h.follows,
      projectType: h.project_type, categories: h.categories, serverSide: h.server_side, clientSide: h.client_side,
    })),
  };
}

async function modrinthProject(slug) {
  const p = await getJSON(`${MODRINTH}/project/${encodeURIComponent(slug)}`);
  return {
    slug: p.slug, title: p.title, description: p.description, body: p.body, iconUrl: p.icon_url,
    downloads: p.downloads, projectType: p.project_type, sourceUrl: p.source_url,
    clientSide: p.client_side, serverSide: p.server_side, gameVersions: p.game_versions, loaders: p.loaders,
  };
}

async function modrinthVersions(slug, { loader, gameVersion } = {}) {
  let url = `${MODRINTH}/project/${encodeURIComponent(slug)}/version`;
  const q = [];
  if (loader) q.push('loaders=' + encodeURIComponent('["' + loader + '"]'));
  if (gameVersion) q.push('game_versions=' + encodeURIComponent('["' + gameVersion + '"]'));
  if (q.length) url += '?' + q.join('&');
  const list = await getJSON(url);
  return (list || []).map((v) => {
    const f = (v.files || []).find((x) => x.primary) || (v.files || [])[0] || {};
    return {
      id: v.id, name: v.name, versionNumber: v.version_number, versionType: v.version_type,
      gameVersions: v.game_versions, loaders: v.loaders, datePublished: v.date_published,
      filename: f.filename, url: f.url, sha512: f.hashes && f.hashes.sha512,
    };
  });
}

async function installFromModrinth(id, { slug, versionId, projectType = 'mod', loader = 'fabric', gameVersion } = {}) {
  if (!cfg.getServer(id)) throw Object.assign(new Error('no such server: ' + id), { status: 404 });
  if (!slug && !versionId) throw Object.assign(new Error('slug or versionId required'), { status: 400 });
  let chosen;
  if (versionId) {
    const v = await getJSON(`${MODRINTH}/version/${encodeURIComponent(versionId)}`);
    const f = (v.files || []).find((x) => x.primary) || (v.files || [])[0];
    if (!f) throw new Error('version has no downloadable file');
    chosen = { filename: f.filename, url: f.url, sha512: f.hashes && f.hashes.sha512, versionNumber: v.version_number };
  } else {
    const vers = await modrinthVersions(slug, { loader: projectType === 'mod' ? loader : undefined, gameVersion });
    if (!vers.length) throw new Error(`no ${loader} version of "${slug}" for MC ${gameVersion}`);
    chosen = vers[0];
  }
  const sub = TYPE_DIRS[projectType] || 'mods';
  const dir = path.join(cfg.serverDir(id), sub);
  await fsp.mkdir(dir, { recursive: true });
  const buf = Buffer.from(await (await fetch(chosen.url, { headers: UA })).arrayBuffer());
  if (chosen.sha512) {
    const got = crypto.createHash('sha512').update(buf).digest('hex');
    if (got !== chosen.sha512) throw new Error('checksum mismatch on ' + chosen.filename);
  }
  await fsp.writeFile(path.join(dir, chosen.filename), buf);
  return { file: chosen.filename, dir: sub, version: chosen.versionNumber };
}

module.exports = {
  metaInfo, gameVersions, createServer, deleteServer, slugify, findFreePort,
  listJars, downloadServerJar, installFabricApi, pruneJars,
  modrinthSearch, modrinthProject, modrinthVersions, installFromModrinth,
};
